name: actions
permissions:
  contents: write
on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 18:00 hrs UTC (00:00 hrs IST)
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Version of Python to use
          # cache: 'pip' # Caches the pip packages to speed up the workflow
      
      - name: Configure Git User
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run script
        run: python upno.py
