name: Daily Script Run
on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at midnight IST
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Configure Git User
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      
      - name: Run script
        run: python upno.py
